stack: "mystack"
services:
  visualizer:
    image: "manomarks/visualizer"
    ports:
    - "5000:8080"
    constraint: "node.role==manager"
    volumes:
    - "docker"
volumes:
  docker:
    type: "bind"
    source: "/var/run/docker.sock"
    target: "/var/run/docker.sock"
