stack: "wordpress"

services:
  wordpress:
    image: "ninja.ijakarta.id/wordpress:latest"
    auth: true
    ports:
      - "8080:80"
    environment:
      - "WORDPRESS_DB_HOST=mysql:3306"
      - "WORDPRESS_DB_PASSWORD=wordpress"
