stack: "postgres"

services:
  postgres:
    image: "ninja.ijakarta.id/postgres:latest"
    port:
      # - "5432:5432" # publish port to host
    environtment:
      - "POSTGRES_PASSWORD=root" # required, postgress super user password
      # - "POSTGRES_USER=[optional]" # optional, to set user password
      # - "PGDATA=[optional]" # optional, new location for database file
      # - "POSTGRES_DB=[optional]" # optional, create new database when starting image.