stack: "wordpress"

services:
  wordpress:
    image: "ninja.ijakarta.id/wordpress:latest"
    auth: true
    endpoint: "80"
    environment:
      - "WORDPRESS_DB_HOST={orcinus.userid}-{orcinus.stack}-mysql:3306"
      - "WORDPRESS_DB_PASSWORD=root"
