stack: "joomla"

services:
  joomla:
    image: "ninja.ijakarta.id/joomla:3.6.5-apache"
    ports:
      - "8080:80"
    depends_on:
      - "joomladb"
    # environment:
    #   - "JOOMLA_DB_PASSWORD=joomla"

  joomladb:
    image: "ninja.ijakarta.id/mysql:latest"
    ports:
    - "3306"
    environment:
    - "MYSQL_ROOT_PASSWORD=joomla"
